# Generated by Django 5.1 on 2024-09-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_rooms_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
