# Generated by Django 5.1 on 2024-09-16 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_room_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='room',
            name='particioants',
            field=models.ManyToManyField(blank=True, related_name='particioants', to=settings.AUTH_USER_MODEL),
        ),
    ]
