# Generated by Django 5.1 on 2024-09-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_message_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='particioants',
            new_name='participants',
        ),
    ]
